# Generated by Django 5.2.12 on 2026-03-04 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('study_type', models.CharField(choices=[('lecture', 'Lecture'), ('reading', 'Reading'), ('revision', 'Revision'), ('practice', 'Practice')], max_length=50)),
                ('duration_mins', models.PositiveIntegerField()),
                ('study_date', models.DateField()),
                ('reflection_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
